//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stagging_tblreportinformation
    {
        public int ReportID { get; set; }
        public string ReportTitle { get; set; }
        public string TableofContents { get; set; }
        public string ListOfTable { get; set; }
        public string ListOfFigure { get; set; }
        public string Summary { get; set; }
        public string FullDescription { get; set; }
        public string ReportImage { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<decimal> PriceSingleUser { get; set; }
        public Nullable<decimal> PriceEnterpriseLicense { get; set; }
        public Nullable<decimal> PriceCUL { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<int> NumberOfPage { get; set; }
        public Nullable<int> Publisher { get; set; }
        public Nullable<int> ReportType { get; set; }
        public Nullable<int> DeliveryFormat { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string ReportUrl { get; set; }
        public string ListOfCharts { get; set; }
    }
}
