//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stagingtblreportinformation
    {
        public int ReportID { get; set; }
        public string ReportTitle { get; set; }
        public string TableofContents { get; set; }
        public string ListOfTable { get; set; }
        public string ListOfFigure { get; set; }
        public string Summary { get; set; }
        public string FullDescription { get; set; }
        public string ReportImage { get; set; }
        public string PublishDate { get; set; }
        public string PriceSingleUser { get; set; }
        public string PriceEnterpriseLicense { get; set; }
        public string PriceCUL { get; set; }
        public string Location { get; set; }
        public string DiscountPercentage { get; set; }
        public string NumberOfPage { get; set; }
        public string Publisher { get; set; }
        public string ReportType { get; set; }
        public string DeliveryFormat { get; set; }
        public string IsActive { get; set; }
        public string IsDeleted { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string ReportUrl { get; set; }
        public string ListOfCharts { get; set; }
    }
}
