//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbuyerinformation
    {
        public int Id { get; set; }
        public string BuyerName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ReportTitle { get; set; }
        public string Country { get; set; }
        public string Email { get; set; }
        public string ContactNumber { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string CompanyName { get; set; }
        public string BuyerAddress { get; set; }
        public string IPAddress { get; set; }
        public string AccessToken { get; set; }
        public string GuId { get; set; }
        public string TransactionId { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string PaymentThrough { get; set; }
        public string City { get; set; }
        public string TransactionStatus { get; set; }
        public string Reason { get; set; }
        public string razorpay_payment_id { get; set; }
        public string razorpay_order_id { get; set; }
    }
}
