//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcolumnvalue
    {
        public int ID { get; set; }
        public Nullable<int> ColumnID { get; set; }
        public string ColumnValue { get; set; }
        public Nullable<int> ReportID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
