//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcategory
    {
        public int pkCategoryID { get; set; }
        public string CategoryName { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public string PageHeading { get; set; }
        public Nullable<int> DomainId { get; set; }
        public string SEOPageName { get; set; }
        public string LinkTitle { get; set; }
        public string TopDescription { get; set; }
        public string BottomDescription { get; set; }
        public string HomePageDescription { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string MetaDescription { get; set; }
        public string SEOContentHeader { get; set; }
        public string SEOFooter { get; set; }
        public string HomePageImagePath { get; set; }
        public string HomePageImageAltAttribute { get; set; }
        public string MainPageImagePath { get; set; }
        public string MainPageImageAltAttribute { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CategoryUrl { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
