//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcountry1
    {
        public string lang { get; set; }
        public string lang_name { get; set; }
        public string country_alpha2_code { get; set; }
        public string country_alpha3_code { get; set; }
        public string country_numeric_code { get; set; }
        public string country_name { get; set; }
        public int id { get; set; }
    }
}
