//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcartitem
    {
        public int Id { get; set; }
        public Nullable<int> CartId { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<int> SelectedType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> ItemAmount { get; set; }
        public Nullable<bool> IsEnable { get; set; }
    }
}
