//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfeedback
    {
        public int FeedbackId { get; set; }
        public string CustomerName { get; set; }
        public string EmailId { get; set; }
        public string Phone { get; set; }
        public string Feedback { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<System.DateTime> FeedbackDateTime { get; set; }
        public Nullable<int> FeedbackFor { get; set; }
        public string Uid { get; set; }
    }
}
