//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinquiry
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string PhoneNumber { get; set; }
        public string Message { get; set; }
        public string ReportId { get; set; }
        public string Type { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> DateOfInquiry { get; set; }
        public string Designation { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsMailSentToAdmin { get; set; }
        public Nullable<bool> IsMailSentToUser { get; set; }
        public string IpAddress { get; set; }
    }
}
