//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbljobvacancy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbljobvacancy()
        {
            this.tbljobapplications = new HashSet<tbljobapplication>();
        }
    
        public int VacancyId { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> NumberOfVacancies { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<System.DateTime> Displaydate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreadtedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> MinYearExperience { get; set; }
        public Nullable<decimal> MaxYearExperience { get; set; }
        public Nullable<bool> CanFresherApply { get; set; }
        public Nullable<System.DateTime> InterviewDateTo { get; set; }
        public string InterviewTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbljobapplication> tbljobapplications { get; set; }
    }
}
