//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblkey
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public Nullable<System.DateTime> GeneratedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsUsed { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UrlKey { get; set; }
        public string TempIPAddress { get; set; }
    }
}
