//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblnew
    {
        public int NewsID { get; set; }
        public string News { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string NewsTitle { get; set; }
        public string NewsUrl { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string MetaKeywords { get; set; }
        public string SearchPageDescription { get; set; }
        public string MainPageImagePath { get; set; }
        public string SearchPageImagePath { get; set; }
        public string MainPageImageAltAttribute { get; set; }
        public string SearchPageImageAltAttribute { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public string PublishedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsArticle { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
