//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpublisher
    {
        public int PublisherID { get; set; }
        public string Publisher { get; set; }
        public string ContactNumber { get; set; }
        public string ContactPerson { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string PublisherWebsite { get; set; }
        public string PublisherUrl { get; set; }
        public string Title { get; set; }
        public string MetaDescription { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
    }
}
