//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpaymentlink
    {
        public int Id { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<decimal> SingleUserPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Description { get; set; }
        public string PaymentLink { get; set; }
        public Nullable<decimal> MultiUserPrice { get; set; }
        public Nullable<decimal> CorporateUserPrice { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
