//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreportinformation
    {
        public int ReportID { get; set; }
        public string ReportTitle { get; set; }
        public string TableofContents { get; set; }
        public string ListOfTable { get; set; }
        public string ListOfFigure { get; set; }
        public string MainPageDescription { get; set; }
        public string SearchPageDescription { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<decimal> PriceSingleUser { get; set; }
        public Nullable<decimal> PriceEnterpriseLicense { get; set; }
        public Nullable<decimal> PriceCUL { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<int> NumberOfPage { get; set; }
        public Nullable<int> Publisher { get; set; }
        public Nullable<int> ReportType { get; set; }
        public Nullable<int> DeliveryFormat { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReportUrl { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string MetaTitle { get; set; }
        public string ListOfCharts { get; set; }
        public Nullable<bool> IsUpComing { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public string Methodology { get; set; }
        public string CategoryBreadCrumb { get; set; }
        public string FreeAnalysis { get; set; }
        public string MainPageImagePath { get; set; }
        public string SearchPageImagePath { get; set; }
        public string MainPageImageAltAttribute { get; set; }
        public string SearchPageImageAltAttribute { get; set; }
        public string Tags { get; set; }
        public string MetaTitleSample { get; set; }
        public string MetaDescriptionSample { get; set; }
        public string MetaKeywordsSample { get; set; }
        public string MetaTitleTOC { get; set; }
        public string MetaDescriptionTOC { get; set; }
        public string MetaKeywordsTOC { get; set; }
        public string MetaTitleFreeAnalysis { get; set; }
        public string MetaDescriptionFreeAnalysis { get; set; }
        public string MetaKeywordsFreeAnalysis { get; set; }
        public string MetaTitleInquiry { get; set; }
        public string MetaDescriptionInquiry { get; set; }
        public string MetaKeywordsInquiry { get; set; }
    }
}
