//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblreseller_reportinformation
    {
        public int ID { get; set; }
        public int ReportID { get; set; }
        public string ReportTitle { get; set; }
        public string MainPageDescription { get; set; }
        public Nullable<bool> IsUpComing { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
    }
}
