//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsearchhistory
    {
        public int Id { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public string SearchText { get; set; }
        public Nullable<int> ReportId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<System.DateTime> SearchDate { get; set; }
    }
}
