//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblzionmail
    {
        public int ID { get; set; }
        public string EmailID { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public Nullable<int> PublisherId { get; set; }
    }
}
