//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Core.Objects.DataClasses;
    using System.Linq;
    
    public partial class zionmysqldbEntities : DbContext
    {
        public zionmysqldbEntities()
            : base("name=zionmysqldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<relactionrole> relactionroles { get; set; }
        public DbSet<relreportbuyer> relreportbuyers { get; set; }
        public DbSet<relreportcategory> relreportcategories { get; set; }
        public DbSet<relreportdomain> relreportdomains { get; set; }
        public DbSet<tblaction> tblactions { get; set; }
        public DbSet<tbladminlogin> tbladminlogins { get; set; }
        public DbSet<tblauthor> tblauthors { get; set; }
        public DbSet<tblbuyerinformation> tblbuyerinformations { get; set; }
        public DbSet<tblcart> tblcarts { get; set; }
        public DbSet<tblcartitem> tblcartitems { get; set; }
        public DbSet<tblcategory> tblcategories { get; set; }
        public DbSet<tblcontinent> tblcontinents { get; set; }
        public DbSet<tblcountry> tblcountries { get; set; }
        public DbSet<tblcountry1> tblcountries1 { get; set; }
        public DbSet<tbldomain> tbldomains { get; set; }
        public DbSet<tblfeedback> tblfeedbacks { get; set; }
        public DbSet<tblform> tblforms { get; set; }
        public DbSet<tblinquiry> tblinquiries { get; set; }
        public DbSet<tblipaddress> tblipaddresses { get; set; }
        public DbSet<tblkey> tblkeys { get; set; }
        public DbSet<tblmail> tblmails { get; set; }
        public DbSet<tblnew> tblnews { get; set; }
        public DbSet<tblpayerinformation> tblpayerinformations { get; set; }
        public DbSet<tblpaymentlink> tblpaymentlinks { get; set; }
        public DbSet<tblpublisher> tblpublishers { get; set; }
        public DbSet<tblredirection> tblredirections { get; set; }
        public DbSet<tblregister> tblregisters { get; set; }
        public DbSet<tblreportinformation> tblreportinformations { get; set; }
        public DbSet<tblreporttype> tblreporttypes { get; set; }
        public DbSet<tblrole> tblroles { get; set; }
        public DbSet<tblsearchhistory> tblsearchhistories { get; set; }
        public DbSet<tblsubscription> tblsubscriptions { get; set; }
        public DbSet<tbltag> tbltags { get; set; }
        public DbSet<tbluserrole> tbluserroles { get; set; }
        public DbSet<tbluser> tblusers { get; set; }
        public DbSet<tblzionmail> tblzionmails { get; set; }
        public DbSet<tblvisitor> tblvisitors { get; set; }
        public DbSet<tblzioninnew> tblzioninnews { get; set; }
        public DbSet<tbljobvacancy> tbljobvacancies { get; set; }
        public DbSet<tbljobapplication> tbljobapplications { get; set; }
        public DbSet<relreportattribute> relreportattributes { get; set; }
        public DbSet<tblreportattribute> tblreportattributes { get; set; }
        public DbSet<tblreportfaq> tblreportfaqs { get; set; }
    
        public virtual ObjectResult<Zion_AddPaymentLink_Result> Zion_AddPaymentLink(string p_ReportUrl, Nullable<System.DateTime> p_ValidTo, Nullable<decimal> p_SingleUserPrice, Nullable<decimal> p_MultiUserPrice, Nullable<decimal> p_CorporateUserPrice, string p_Description, Nullable<int> p_CreatedBy, ObjectParameter p_LinkUrl)
        {
            var p_ReportUrlParameter = p_ReportUrl != null ?
                new ObjectParameter("p_ReportUrl", p_ReportUrl) :
                new ObjectParameter("p_ReportUrl", typeof(string));
    
            var p_ValidToParameter = p_ValidTo.HasValue ?
                new ObjectParameter("p_ValidTo", p_ValidTo) :
                new ObjectParameter("p_ValidTo", typeof(System.DateTime));
    
            var p_SingleUserPriceParameter = p_SingleUserPrice.HasValue ?
                new ObjectParameter("p_SingleUserPrice", p_SingleUserPrice) :
                new ObjectParameter("p_SingleUserPrice", typeof(decimal));
    
            var p_MultiUserPriceParameter = p_MultiUserPrice.HasValue ?
                new ObjectParameter("p_MultiUserPrice", p_MultiUserPrice) :
                new ObjectParameter("p_MultiUserPrice", typeof(decimal));
    
            var p_CorporateUserPriceParameter = p_CorporateUserPrice.HasValue ?
                new ObjectParameter("p_CorporateUserPrice", p_CorporateUserPrice) :
                new ObjectParameter("p_CorporateUserPrice", typeof(decimal));
    
            var p_DescriptionParameter = p_Description != null ?
                new ObjectParameter("p_Description", p_Description) :
                new ObjectParameter("p_Description", typeof(string));
    
            var p_CreatedByParameter = p_CreatedBy.HasValue ?
                new ObjectParameter("p_CreatedBy", p_CreatedBy) :
                new ObjectParameter("p_CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zion_AddPaymentLink_Result>("Zion_AddPaymentLink", p_ReportUrlParameter, p_ValidToParameter, p_SingleUserPriceParameter, p_MultiUserPriceParameter, p_CorporateUserPriceParameter, p_DescriptionParameter, p_CreatedByParameter, p_LinkUrl);
        }
    
        public virtual int Zion_AddRedirectUrl(string p_FromUrl, string p_ToUrl, Nullable<int> p_CreatedBy)
        {
            var p_FromUrlParameter = p_FromUrl != null ?
                new ObjectParameter("p_FromUrl", p_FromUrl) :
                new ObjectParameter("p_FromUrl", typeof(string));
    
            var p_ToUrlParameter = p_ToUrl != null ?
                new ObjectParameter("p_ToUrl", p_ToUrl) :
                new ObjectParameter("p_ToUrl", typeof(string));
    
            var p_CreatedByParameter = p_CreatedBy.HasValue ?
                new ObjectParameter("p_CreatedBy", p_CreatedBy) :
                new ObjectParameter("p_CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_AddRedirectUrl", p_FromUrlParameter, p_ToUrlParameter, p_CreatedByParameter);
        }
    
        public virtual int Zion_AddRole(string p_RoleName, string p_Actions, Nullable<int> p_CreatedBy)
        {
            var p_RoleNameParameter = p_RoleName != null ?
                new ObjectParameter("p_RoleName", p_RoleName) :
                new ObjectParameter("p_RoleName", typeof(string));
    
            var p_ActionsParameter = p_Actions != null ?
                new ObjectParameter("p_Actions", p_Actions) :
                new ObjectParameter("p_Actions", typeof(string));
    
            var p_CreatedByParameter = p_CreatedBy.HasValue ?
                new ObjectParameter("p_CreatedBy", p_CreatedBy) :
                new ObjectParameter("p_CreatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_AddRole", p_RoleNameParameter, p_ActionsParameter, p_CreatedByParameter);
        }
    
        public virtual int Zion_AddUserRole(Nullable<int> p_UserId, string p_RoleIdList)
        {
            var p_UserIdParameter = p_UserId.HasValue ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(int));
    
            var p_RoleIdListParameter = p_RoleIdList != null ?
                new ObjectParameter("p_RoleIdList", p_RoleIdList) :
                new ObjectParameter("p_RoleIdList", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_AddUserRole", p_UserIdParameter, p_RoleIdListParameter);
        }
    
        public virtual ObjectResult<Zion_GetAllCountry_Result> Zion_GetAllCountry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zion_GetAllCountry_Result>("Zion_GetAllCountry");
        }
    
        public virtual ObjectResult<Zion_GetAllPublishedReports_Result> Zion_GetAllPublishedReports(Nullable<int> p_Page, ObjectParameter p_TotalRecords)
        {
            var p_PageParameter = p_Page.HasValue ?
                new ObjectParameter("p_Page", p_Page) :
                new ObjectParameter("p_Page", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zion_GetAllPublishedReports_Result>("Zion_GetAllPublishedReports", p_PageParameter, p_TotalRecords);
        }
    
        public virtual ObjectResult<Zion_GetAllUpcomingReports_Result> Zion_GetAllUpcomingReports(Nullable<int> p_Page, ObjectParameter p_TotalRecords)
        {
            var p_PageParameter = p_Page.HasValue ?
                new ObjectParameter("p_Page", p_Page) :
                new ObjectParameter("p_Page", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zion_GetAllUpcomingReports_Result>("Zion_GetAllUpcomingReports", p_PageParameter, p_TotalRecords);
        }
    
        public virtual ObjectResult<Zion_GetCategoryWithReportCount_Result> Zion_GetCategoryWithReportCount()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zion_GetCategoryWithReportCount_Result>("Zion_GetCategoryWithReportCount");
        }
    
        public virtual int Zion_AddNews(Nullable<int> p_CategoryId, string p_Description, Nullable<int> p_CreatedBy, string p_Title, string p_NewsUrl, string p_ReportUrl, string p_MetaTitle, string p_MetaDescription, string p_MetaKeywords, string p_SearchPageDescription, string p_MainPageImagePath, string p_SearchPageImagePath, string p_MainPageImageAltAttribute, string p_SearchPageImageAltAttribute, string p_PublishedBy, Nullable<System.DateTime> p_PublishedDate, ObjectParameter p_Message, Nullable<sbyte> p_AppendId, Nullable<sbyte> p_IsArticle, Nullable<sbyte> p_IsActive)
        {
            var p_CategoryIdParameter = p_CategoryId.HasValue ?
                new ObjectParameter("p_CategoryId", p_CategoryId) :
                new ObjectParameter("p_CategoryId", typeof(int));
    
            var p_DescriptionParameter = p_Description != null ?
                new ObjectParameter("p_Description", p_Description) :
                new ObjectParameter("p_Description", typeof(string));
    
            var p_CreatedByParameter = p_CreatedBy.HasValue ?
                new ObjectParameter("p_CreatedBy", p_CreatedBy) :
                new ObjectParameter("p_CreatedBy", typeof(int));
    
            var p_TitleParameter = p_Title != null ?
                new ObjectParameter("p_Title", p_Title) :
                new ObjectParameter("p_Title", typeof(string));
    
            var p_NewsUrlParameter = p_NewsUrl != null ?
                new ObjectParameter("p_NewsUrl", p_NewsUrl) :
                new ObjectParameter("p_NewsUrl", typeof(string));
    
            var p_ReportUrlParameter = p_ReportUrl != null ?
                new ObjectParameter("p_ReportUrl", p_ReportUrl) :
                new ObjectParameter("p_ReportUrl", typeof(string));
    
            var p_MetaTitleParameter = p_MetaTitle != null ?
                new ObjectParameter("p_MetaTitle", p_MetaTitle) :
                new ObjectParameter("p_MetaTitle", typeof(string));
    
            var p_MetaDescriptionParameter = p_MetaDescription != null ?
                new ObjectParameter("p_MetaDescription", p_MetaDescription) :
                new ObjectParameter("p_MetaDescription", typeof(string));
    
            var p_MetaKeywordsParameter = p_MetaKeywords != null ?
                new ObjectParameter("p_MetaKeywords", p_MetaKeywords) :
                new ObjectParameter("p_MetaKeywords", typeof(string));
    
            var p_SearchPageDescriptionParameter = p_SearchPageDescription != null ?
                new ObjectParameter("p_SearchPageDescription", p_SearchPageDescription) :
                new ObjectParameter("p_SearchPageDescription", typeof(string));
    
            var p_MainPageImagePathParameter = p_MainPageImagePath != null ?
                new ObjectParameter("p_MainPageImagePath", p_MainPageImagePath) :
                new ObjectParameter("p_MainPageImagePath", typeof(string));
    
            var p_SearchPageImagePathParameter = p_SearchPageImagePath != null ?
                new ObjectParameter("p_SearchPageImagePath", p_SearchPageImagePath) :
                new ObjectParameter("p_SearchPageImagePath", typeof(string));
    
            var p_MainPageImageAltAttributeParameter = p_MainPageImageAltAttribute != null ?
                new ObjectParameter("p_MainPageImageAltAttribute", p_MainPageImageAltAttribute) :
                new ObjectParameter("p_MainPageImageAltAttribute", typeof(string));
    
            var p_SearchPageImageAltAttributeParameter = p_SearchPageImageAltAttribute != null ?
                new ObjectParameter("p_SearchPageImageAltAttribute", p_SearchPageImageAltAttribute) :
                new ObjectParameter("p_SearchPageImageAltAttribute", typeof(string));
    
            var p_PublishedByParameter = p_PublishedBy != null ?
                new ObjectParameter("p_PublishedBy", p_PublishedBy) :
                new ObjectParameter("p_PublishedBy", typeof(string));
    
            var p_PublishedDateParameter = p_PublishedDate.HasValue ?
                new ObjectParameter("p_PublishedDate", p_PublishedDate) :
                new ObjectParameter("p_PublishedDate", typeof(System.DateTime));
    
            var p_AppendIdParameter = p_AppendId.HasValue ?
                new ObjectParameter("p_AppendId", p_AppendId) :
                new ObjectParameter("p_AppendId", typeof(sbyte));
    
            var p_IsArticleParameter = p_IsArticle.HasValue ?
                new ObjectParameter("p_IsArticle", p_IsArticle) :
                new ObjectParameter("p_IsArticle", typeof(sbyte));
    
            var p_IsActiveParameter = p_IsActive.HasValue ?
                new ObjectParameter("p_IsActive", p_IsActive) :
                new ObjectParameter("p_IsActive", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_AddNews", p_CategoryIdParameter, p_DescriptionParameter, p_CreatedByParameter, p_TitleParameter, p_NewsUrlParameter, p_ReportUrlParameter, p_MetaTitleParameter, p_MetaDescriptionParameter, p_MetaKeywordsParameter, p_SearchPageDescriptionParameter, p_MainPageImagePathParameter, p_SearchPageImagePathParameter, p_MainPageImageAltAttributeParameter, p_SearchPageImageAltAttributeParameter, p_PublishedByParameter, p_PublishedDateParameter, p_Message, p_AppendIdParameter, p_IsArticleParameter, p_IsActiveParameter);
        }
    
        public virtual int Zion_UpdateCategory(Nullable<int> p_CategoryId, string p_CategoryUrl, string p_CategoryName, Nullable<int> p_ParentCategoryId, string p_Title, string p_Description, string p_PageHeading, string p_MainPageImagePath, string p_MainPageImageAltAttribute, string p_HomePageDescription, string p_HomePageImagePath, string p_HomePageImageAltAttribute, string p_MetaDescription, string p_Keyword, Nullable<int> p_UserId)
        {
            var p_CategoryIdParameter = p_CategoryId.HasValue ?
                new ObjectParameter("p_CategoryId", p_CategoryId) :
                new ObjectParameter("p_CategoryId", typeof(int));
    
            var p_CategoryUrlParameter = p_CategoryUrl != null ?
                new ObjectParameter("p_CategoryUrl", p_CategoryUrl) :
                new ObjectParameter("p_CategoryUrl", typeof(string));
    
            var p_CategoryNameParameter = p_CategoryName != null ?
                new ObjectParameter("p_CategoryName", p_CategoryName) :
                new ObjectParameter("p_CategoryName", typeof(string));
    
            var p_ParentCategoryIdParameter = p_ParentCategoryId.HasValue ?
                new ObjectParameter("p_ParentCategoryId", p_ParentCategoryId) :
                new ObjectParameter("p_ParentCategoryId", typeof(int));
    
            var p_TitleParameter = p_Title != null ?
                new ObjectParameter("p_Title", p_Title) :
                new ObjectParameter("p_Title", typeof(string));
    
            var p_DescriptionParameter = p_Description != null ?
                new ObjectParameter("p_Description", p_Description) :
                new ObjectParameter("p_Description", typeof(string));
    
            var p_PageHeadingParameter = p_PageHeading != null ?
                new ObjectParameter("p_PageHeading", p_PageHeading) :
                new ObjectParameter("p_PageHeading", typeof(string));
    
            var p_MainPageImagePathParameter = p_MainPageImagePath != null ?
                new ObjectParameter("p_MainPageImagePath", p_MainPageImagePath) :
                new ObjectParameter("p_MainPageImagePath", typeof(string));
    
            var p_MainPageImageAltAttributeParameter = p_MainPageImageAltAttribute != null ?
                new ObjectParameter("p_MainPageImageAltAttribute", p_MainPageImageAltAttribute) :
                new ObjectParameter("p_MainPageImageAltAttribute", typeof(string));
    
            var p_HomePageDescriptionParameter = p_HomePageDescription != null ?
                new ObjectParameter("p_HomePageDescription", p_HomePageDescription) :
                new ObjectParameter("p_HomePageDescription", typeof(string));
    
            var p_HomePageImagePathParameter = p_HomePageImagePath != null ?
                new ObjectParameter("p_HomePageImagePath", p_HomePageImagePath) :
                new ObjectParameter("p_HomePageImagePath", typeof(string));
    
            var p_HomePageImageAltAttributeParameter = p_HomePageImageAltAttribute != null ?
                new ObjectParameter("p_HomePageImageAltAttribute", p_HomePageImageAltAttribute) :
                new ObjectParameter("p_HomePageImageAltAttribute", typeof(string));
    
            var p_MetaDescriptionParameter = p_MetaDescription != null ?
                new ObjectParameter("p_MetaDescription", p_MetaDescription) :
                new ObjectParameter("p_MetaDescription", typeof(string));
    
            var p_KeywordParameter = p_Keyword != null ?
                new ObjectParameter("p_Keyword", p_Keyword) :
                new ObjectParameter("p_Keyword", typeof(string));
    
            var p_UserIdParameter = p_UserId.HasValue ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_UpdateCategory", p_CategoryIdParameter, p_CategoryUrlParameter, p_CategoryNameParameter, p_ParentCategoryIdParameter, p_TitleParameter, p_DescriptionParameter, p_PageHeadingParameter, p_MainPageImagePathParameter, p_MainPageImageAltAttributeParameter, p_HomePageDescriptionParameter, p_HomePageImagePathParameter, p_HomePageImageAltAttributeParameter, p_MetaDescriptionParameter, p_KeywordParameter, p_UserIdParameter);
        }
    
        public virtual int Zion_UpdateNews(Nullable<int> p_CategoryId, string p_Description, Nullable<int> p_UpdatedBy, string p_Title, Nullable<int> p_NewsId, string p_ReportUrl, string p_NewsUrl, string p_SearchPageDescription, string p_MainPageImagePath, string p_SearchPageImagePath, string p_MainPageAltAttribute, string p_SearchPageImageAltAttribute, string p_MetaTitle, string p_MetaDescription, string p_MetaKeywords, Nullable<System.DateTime> p_PublishedDate, string p_PublishedBy, Nullable<sbyte> p_IsArticle, Nullable<sbyte> p_IsActive)
        {
            var p_CategoryIdParameter = p_CategoryId.HasValue ?
                new ObjectParameter("p_CategoryId", p_CategoryId) :
                new ObjectParameter("p_CategoryId", typeof(int));
    
            var p_DescriptionParameter = p_Description != null ?
                new ObjectParameter("p_Description", p_Description) :
                new ObjectParameter("p_Description", typeof(string));
    
            var p_UpdatedByParameter = p_UpdatedBy.HasValue ?
                new ObjectParameter("p_UpdatedBy", p_UpdatedBy) :
                new ObjectParameter("p_UpdatedBy", typeof(int));
    
            var p_TitleParameter = p_Title != null ?
                new ObjectParameter("p_Title", p_Title) :
                new ObjectParameter("p_Title", typeof(string));
    
            var p_NewsIdParameter = p_NewsId.HasValue ?
                new ObjectParameter("p_NewsId", p_NewsId) :
                new ObjectParameter("p_NewsId", typeof(int));
    
            var p_ReportUrlParameter = p_ReportUrl != null ?
                new ObjectParameter("p_ReportUrl", p_ReportUrl) :
                new ObjectParameter("p_ReportUrl", typeof(string));
    
            var p_NewsUrlParameter = p_NewsUrl != null ?
                new ObjectParameter("p_NewsUrl", p_NewsUrl) :
                new ObjectParameter("p_NewsUrl", typeof(string));
    
            var p_SearchPageDescriptionParameter = p_SearchPageDescription != null ?
                new ObjectParameter("p_SearchPageDescription", p_SearchPageDescription) :
                new ObjectParameter("p_SearchPageDescription", typeof(string));
    
            var p_MainPageImagePathParameter = p_MainPageImagePath != null ?
                new ObjectParameter("p_MainPageImagePath", p_MainPageImagePath) :
                new ObjectParameter("p_MainPageImagePath", typeof(string));
    
            var p_SearchPageImagePathParameter = p_SearchPageImagePath != null ?
                new ObjectParameter("p_SearchPageImagePath", p_SearchPageImagePath) :
                new ObjectParameter("p_SearchPageImagePath", typeof(string));
    
            var p_MainPageAltAttributeParameter = p_MainPageAltAttribute != null ?
                new ObjectParameter("p_MainPageAltAttribute", p_MainPageAltAttribute) :
                new ObjectParameter("p_MainPageAltAttribute", typeof(string));
    
            var p_SearchPageImageAltAttributeParameter = p_SearchPageImageAltAttribute != null ?
                new ObjectParameter("p_SearchPageImageAltAttribute", p_SearchPageImageAltAttribute) :
                new ObjectParameter("p_SearchPageImageAltAttribute", typeof(string));
    
            var p_MetaTitleParameter = p_MetaTitle != null ?
                new ObjectParameter("p_MetaTitle", p_MetaTitle) :
                new ObjectParameter("p_MetaTitle", typeof(string));
    
            var p_MetaDescriptionParameter = p_MetaDescription != null ?
                new ObjectParameter("p_MetaDescription", p_MetaDescription) :
                new ObjectParameter("p_MetaDescription", typeof(string));
    
            var p_MetaKeywordsParameter = p_MetaKeywords != null ?
                new ObjectParameter("p_MetaKeywords", p_MetaKeywords) :
                new ObjectParameter("p_MetaKeywords", typeof(string));
    
            var p_PublishedDateParameter = p_PublishedDate.HasValue ?
                new ObjectParameter("p_PublishedDate", p_PublishedDate) :
                new ObjectParameter("p_PublishedDate", typeof(System.DateTime));
    
            var p_PublishedByParameter = p_PublishedBy != null ?
                new ObjectParameter("p_PublishedBy", p_PublishedBy) :
                new ObjectParameter("p_PublishedBy", typeof(string));
    
            var p_IsArticleParameter = p_IsArticle.HasValue ?
                new ObjectParameter("p_IsArticle", p_IsArticle) :
                new ObjectParameter("p_IsArticle", typeof(sbyte));
    
            var p_IsActiveParameter = p_IsActive.HasValue ?
                new ObjectParameter("p_IsActive", p_IsActive) :
                new ObjectParameter("p_IsActive", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_UpdateNews", p_CategoryIdParameter, p_DescriptionParameter, p_UpdatedByParameter, p_TitleParameter, p_NewsIdParameter, p_ReportUrlParameter, p_NewsUrlParameter, p_SearchPageDescriptionParameter, p_MainPageImagePathParameter, p_SearchPageImagePathParameter, p_MainPageAltAttributeParameter, p_SearchPageImageAltAttributeParameter, p_MetaTitleParameter, p_MetaDescriptionParameter, p_MetaKeywordsParameter, p_PublishedDateParameter, p_PublishedByParameter, p_IsArticleParameter, p_IsActiveParameter);
        }
    
        public virtual int Zion_UpdatePaymentLInk(Nullable<int> p_Id, Nullable<decimal> p_SingleUserPrice, Nullable<decimal> p_MultiUserPrice, Nullable<decimal> p_CorporateUserPrice, Nullable<System.DateTime> p_ValidTo, string p_Description, Nullable<int> p_UpdatedBy)
        {
            var p_IdParameter = p_Id.HasValue ?
                new ObjectParameter("p_Id", p_Id) :
                new ObjectParameter("p_Id", typeof(int));
    
            var p_SingleUserPriceParameter = p_SingleUserPrice.HasValue ?
                new ObjectParameter("p_SingleUserPrice", p_SingleUserPrice) :
                new ObjectParameter("p_SingleUserPrice", typeof(decimal));
    
            var p_MultiUserPriceParameter = p_MultiUserPrice.HasValue ?
                new ObjectParameter("p_MultiUserPrice", p_MultiUserPrice) :
                new ObjectParameter("p_MultiUserPrice", typeof(decimal));
    
            var p_CorporateUserPriceParameter = p_CorporateUserPrice.HasValue ?
                new ObjectParameter("p_CorporateUserPrice", p_CorporateUserPrice) :
                new ObjectParameter("p_CorporateUserPrice", typeof(decimal));
    
            var p_ValidToParameter = p_ValidTo.HasValue ?
                new ObjectParameter("p_ValidTo", p_ValidTo) :
                new ObjectParameter("p_ValidTo", typeof(System.DateTime));
    
            var p_DescriptionParameter = p_Description != null ?
                new ObjectParameter("p_Description", p_Description) :
                new ObjectParameter("p_Description", typeof(string));
    
            var p_UpdatedByParameter = p_UpdatedBy.HasValue ?
                new ObjectParameter("p_UpdatedBy", p_UpdatedBy) :
                new ObjectParameter("p_UpdatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_UpdatePaymentLInk", p_IdParameter, p_SingleUserPriceParameter, p_MultiUserPriceParameter, p_CorporateUserPriceParameter, p_ValidToParameter, p_DescriptionParameter, p_UpdatedByParameter);
        }
    
        public virtual int Zion_UpdateRedrectUrl(Nullable<int> p_Id, string p_FromUrl, string p_ToUrl, Nullable<int> p_UserId)
        {
            var p_IdParameter = p_Id.HasValue ?
                new ObjectParameter("p_Id", p_Id) :
                new ObjectParameter("p_Id", typeof(int));
    
            var p_FromUrlParameter = p_FromUrl != null ?
                new ObjectParameter("p_FromUrl", p_FromUrl) :
                new ObjectParameter("p_FromUrl", typeof(string));
    
            var p_ToUrlParameter = p_ToUrl != null ?
                new ObjectParameter("p_ToUrl", p_ToUrl) :
                new ObjectParameter("p_ToUrl", typeof(string));
    
            var p_UserIdParameter = p_UserId.HasValue ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_UpdateRedrectUrl", p_IdParameter, p_FromUrlParameter, p_ToUrlParameter, p_UserIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Zion_UpdateReportInformation(Nullable<int> p_ReportId, string p_ReportTitle, string p_TableofContents, string p_ListOfTable, string p_ListOfFigure, string p_MainPageDescription, string p_SearchPageDescription, Nullable<System.DateTime> p_PublishDate, Nullable<decimal> p_SingleUser, Nullable<decimal> p_MultiUser, Nullable<decimal> p_CorporateUser, string p_Location, Nullable<decimal> p_DiscountPercentage, Nullable<int> p_NumberOfPage, string p_MetaTitle, string p_MetaDescription, string p_MetaKeywords, string p_ListOfCharts, string p_ReportUrl, Nullable<int> p_CategoryId, Nullable<sbyte> p_IsActive, Nullable<int> p_UserId, string p_Methodology, Nullable<sbyte> p_IsUpcoming, string p_FreeAnalysis, string p_MainPageImagePath, string p_SearchPageImagePath, string p_MainPageImageAltAttribute, string p_SearchPageImageAltAttribute, ObjectParameter p_UpdateReportId, ObjectParameter p_UpdateReportTitle, ObjectParameter p_UpdateCategory, ObjectParameter p_UpdateReportUrl, ObjectParameter p_RowCount, Nullable<int> p_DeliveryFormat, string p_SampleMetaTitle, string p_SampleMetaDescription, string p_SampleMetaKeywords, string p_TOCMetaTile, string p_TOCMetaDescription, string p_TOCMetaKeywords, string p_FreeAnalysisMetaTitle, string p_FreeAnalysisMetaDescription, string p_FreeAnalysisMetaKeyords, string p_InquiryMetaTitle, string p_InquiryMetaDescription, string p_InquiryMetaKeywords)
        {
            var p_ReportIdParameter = p_ReportId.HasValue ?
                new ObjectParameter("p_ReportId", p_ReportId) :
                new ObjectParameter("p_ReportId", typeof(int));
    
            var p_ReportTitleParameter = p_ReportTitle != null ?
                new ObjectParameter("p_ReportTitle", p_ReportTitle) :
                new ObjectParameter("p_ReportTitle", typeof(string));
    
            var p_TableofContentsParameter = p_TableofContents != null ?
                new ObjectParameter("p_TableofContents", p_TableofContents) :
                new ObjectParameter("p_TableofContents", typeof(string));
    
            var p_ListOfTableParameter = p_ListOfTable != null ?
                new ObjectParameter("p_ListOfTable", p_ListOfTable) :
                new ObjectParameter("p_ListOfTable", typeof(string));
    
            var p_ListOfFigureParameter = p_ListOfFigure != null ?
                new ObjectParameter("p_ListOfFigure", p_ListOfFigure) :
                new ObjectParameter("p_ListOfFigure", typeof(string));
    
            var p_MainPageDescriptionParameter = p_MainPageDescription != null ?
                new ObjectParameter("p_MainPageDescription", p_MainPageDescription) :
                new ObjectParameter("p_MainPageDescription", typeof(string));
    
            var p_SearchPageDescriptionParameter = p_SearchPageDescription != null ?
                new ObjectParameter("p_SearchPageDescription", p_SearchPageDescription) :
                new ObjectParameter("p_SearchPageDescription", typeof(string));
    
            var p_PublishDateParameter = p_PublishDate.HasValue ?
                new ObjectParameter("p_PublishDate", p_PublishDate) :
                new ObjectParameter("p_PublishDate", typeof(System.DateTime));
    
            var p_SingleUserParameter = p_SingleUser.HasValue ?
                new ObjectParameter("p_SingleUser", p_SingleUser) :
                new ObjectParameter("p_SingleUser", typeof(decimal));
    
            var p_MultiUserParameter = p_MultiUser.HasValue ?
                new ObjectParameter("p_MultiUser", p_MultiUser) :
                new ObjectParameter("p_MultiUser", typeof(decimal));
    
            var p_CorporateUserParameter = p_CorporateUser.HasValue ?
                new ObjectParameter("p_CorporateUser", p_CorporateUser) :
                new ObjectParameter("p_CorporateUser", typeof(decimal));
    
            var p_LocationParameter = p_Location != null ?
                new ObjectParameter("p_Location", p_Location) :
                new ObjectParameter("p_Location", typeof(string));
    
            var p_DiscountPercentageParameter = p_DiscountPercentage.HasValue ?
                new ObjectParameter("p_DiscountPercentage", p_DiscountPercentage) :
                new ObjectParameter("p_DiscountPercentage", typeof(decimal));
    
            var p_NumberOfPageParameter = p_NumberOfPage.HasValue ?
                new ObjectParameter("p_NumberOfPage", p_NumberOfPage) :
                new ObjectParameter("p_NumberOfPage", typeof(int));
    
            var p_MetaTitleParameter = p_MetaTitle != null ?
                new ObjectParameter("p_MetaTitle", p_MetaTitle) :
                new ObjectParameter("p_MetaTitle", typeof(string));
    
            var p_MetaDescriptionParameter = p_MetaDescription != null ?
                new ObjectParameter("p_MetaDescription", p_MetaDescription) :
                new ObjectParameter("p_MetaDescription", typeof(string));
    
            var p_MetaKeywordsParameter = p_MetaKeywords != null ?
                new ObjectParameter("p_MetaKeywords", p_MetaKeywords) :
                new ObjectParameter("p_MetaKeywords", typeof(string));
    
            var p_ListOfChartsParameter = p_ListOfCharts != null ?
                new ObjectParameter("p_ListOfCharts", p_ListOfCharts) :
                new ObjectParameter("p_ListOfCharts", typeof(string));
    
            var p_ReportUrlParameter = p_ReportUrl != null ?
                new ObjectParameter("p_ReportUrl", p_ReportUrl) :
                new ObjectParameter("p_ReportUrl", typeof(string));
    
            var p_CategoryIdParameter = p_CategoryId.HasValue ?
                new ObjectParameter("p_CategoryId", p_CategoryId) :
                new ObjectParameter("p_CategoryId", typeof(int));
    
            var p_IsActiveParameter = p_IsActive.HasValue ?
                new ObjectParameter("p_IsActive", p_IsActive) :
                new ObjectParameter("p_IsActive", typeof(sbyte));
    
            var p_UserIdParameter = p_UserId.HasValue ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(int));
    
            var p_MethodologyParameter = p_Methodology != null ?
                new ObjectParameter("p_Methodology", p_Methodology) :
                new ObjectParameter("p_Methodology", typeof(string));
    
            var p_IsUpcomingParameter = p_IsUpcoming.HasValue ?
                new ObjectParameter("p_IsUpcoming", p_IsUpcoming) :
                new ObjectParameter("p_IsUpcoming", typeof(sbyte));
    
            var p_FreeAnalysisParameter = p_FreeAnalysis != null ?
                new ObjectParameter("p_FreeAnalysis", p_FreeAnalysis) :
                new ObjectParameter("p_FreeAnalysis", typeof(string));
    
            var p_MainPageImagePathParameter = p_MainPageImagePath != null ?
                new ObjectParameter("p_MainPageImagePath", p_MainPageImagePath) :
                new ObjectParameter("p_MainPageImagePath", typeof(string));
    
            var p_SearchPageImagePathParameter = p_SearchPageImagePath != null ?
                new ObjectParameter("p_SearchPageImagePath", p_SearchPageImagePath) :
                new ObjectParameter("p_SearchPageImagePath", typeof(string));
    
            var p_MainPageImageAltAttributeParameter = p_MainPageImageAltAttribute != null ?
                new ObjectParameter("p_MainPageImageAltAttribute", p_MainPageImageAltAttribute) :
                new ObjectParameter("p_MainPageImageAltAttribute", typeof(string));
    
            var p_SearchPageImageAltAttributeParameter = p_SearchPageImageAltAttribute != null ?
                new ObjectParameter("p_SearchPageImageAltAttribute", p_SearchPageImageAltAttribute) :
                new ObjectParameter("p_SearchPageImageAltAttribute", typeof(string));
    
            var p_DeliveryFormatParameter = p_DeliveryFormat.HasValue ?
                new ObjectParameter("p_DeliveryFormat", p_DeliveryFormat) :
                new ObjectParameter("p_DeliveryFormat", typeof(int));
    
            var p_SampleMetaTitleParameter = p_SampleMetaTitle != null ?
                new ObjectParameter("p_SampleMetaTitle", p_SampleMetaTitle) :
                new ObjectParameter("p_SampleMetaTitle", typeof(string));
    
            var p_SampleMetaDescriptionParameter = p_SampleMetaDescription != null ?
                new ObjectParameter("p_SampleMetaDescription", p_SampleMetaDescription) :
                new ObjectParameter("p_SampleMetaDescription", typeof(string));
    
            var p_SampleMetaKeywordsParameter = p_SampleMetaKeywords != null ?
                new ObjectParameter("p_SampleMetaKeywords", p_SampleMetaKeywords) :
                new ObjectParameter("p_SampleMetaKeywords", typeof(string));
    
            var p_TOCMetaTileParameter = p_TOCMetaTile != null ?
                new ObjectParameter("p_TOCMetaTile", p_TOCMetaTile) :
                new ObjectParameter("p_TOCMetaTile", typeof(string));
    
            var p_TOCMetaDescriptionParameter = p_TOCMetaDescription != null ?
                new ObjectParameter("p_TOCMetaDescription", p_TOCMetaDescription) :
                new ObjectParameter("p_TOCMetaDescription", typeof(string));
    
            var p_TOCMetaKeywordsParameter = p_TOCMetaKeywords != null ?
                new ObjectParameter("p_TOCMetaKeywords", p_TOCMetaKeywords) :
                new ObjectParameter("p_TOCMetaKeywords", typeof(string));
    
            var p_FreeAnalysisMetaTitleParameter = p_FreeAnalysisMetaTitle != null ?
                new ObjectParameter("p_FreeAnalysisMetaTitle", p_FreeAnalysisMetaTitle) :
                new ObjectParameter("p_FreeAnalysisMetaTitle", typeof(string));
    
            var p_FreeAnalysisMetaDescriptionParameter = p_FreeAnalysisMetaDescription != null ?
                new ObjectParameter("p_FreeAnalysisMetaDescription", p_FreeAnalysisMetaDescription) :
                new ObjectParameter("p_FreeAnalysisMetaDescription", typeof(string));
    
            var p_FreeAnalysisMetaKeyordsParameter = p_FreeAnalysisMetaKeyords != null ?
                new ObjectParameter("p_FreeAnalysisMetaKeyords", p_FreeAnalysisMetaKeyords) :
                new ObjectParameter("p_FreeAnalysisMetaKeyords", typeof(string));
    
            var p_InquiryMetaTitleParameter = p_InquiryMetaTitle != null ?
                new ObjectParameter("p_InquiryMetaTitle", p_InquiryMetaTitle) :
                new ObjectParameter("p_InquiryMetaTitle", typeof(string));
    
            var p_InquiryMetaDescriptionParameter = p_InquiryMetaDescription != null ?
                new ObjectParameter("p_InquiryMetaDescription", p_InquiryMetaDescription) :
                new ObjectParameter("p_InquiryMetaDescription", typeof(string));
    
            var p_InquiryMetaKeywordsParameter = p_InquiryMetaKeywords != null ?
                new ObjectParameter("p_InquiryMetaKeywords", p_InquiryMetaKeywords) :
                new ObjectParameter("p_InquiryMetaKeywords", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Zion_UpdateReportInformation", p_ReportIdParameter, p_ReportTitleParameter, p_TableofContentsParameter, p_ListOfTableParameter, p_ListOfFigureParameter, p_MainPageDescriptionParameter, p_SearchPageDescriptionParameter, p_PublishDateParameter, p_SingleUserParameter, p_MultiUserParameter, p_CorporateUserParameter, p_LocationParameter, p_DiscountPercentageParameter, p_NumberOfPageParameter, p_MetaTitleParameter, p_MetaDescriptionParameter, p_MetaKeywordsParameter, p_ListOfChartsParameter, p_ReportUrlParameter, p_CategoryIdParameter, p_IsActiveParameter, p_UserIdParameter, p_MethodologyParameter, p_IsUpcomingParameter, p_FreeAnalysisParameter, p_MainPageImagePathParameter, p_SearchPageImagePathParameter, p_MainPageImageAltAttributeParameter, p_SearchPageImageAltAttributeParameter, p_UpdateReportId, p_UpdateReportTitle, p_UpdateCategory, p_UpdateReportUrl, p_RowCount, p_DeliveryFormatParameter, p_SampleMetaTitleParameter, p_SampleMetaDescriptionParameter, p_SampleMetaKeywordsParameter, p_TOCMetaTileParameter, p_TOCMetaDescriptionParameter, p_TOCMetaKeywordsParameter, p_FreeAnalysisMetaTitleParameter, p_FreeAnalysisMetaDescriptionParameter, p_FreeAnalysisMetaKeyordsParameter, p_InquiryMetaTitleParameter, p_InquiryMetaDescriptionParameter, p_InquiryMetaKeywordsParameter);
        }
    
        public virtual int Zion_AddCategory(string p_CategoryName, string p_CategoryUrl, Nullable<int> p_ParentCategoryId, string p_PageHeading, string p_Title, string p_TopDescription, string p_MainPageImage, string p_MainPageImageAltAttr, string p_HomePageDesc, string p_HomePageImage, string p_HomePageAltAttr, string p_Keyword, string p_MetaDescription, ObjectParameter p_Message, Nullable<sbyte> p_AppendId, Nullable<int> p_UserId)
        {
            var p_CategoryNameParameter = p_CategoryName != null ?
                new ObjectParameter("p_CategoryName", p_CategoryName) :
                new ObjectParameter("p_CategoryName", typeof(string));
    
            var p_CategoryUrlParameter = p_CategoryUrl != null ?
                new ObjectParameter("p_CategoryUrl", p_CategoryUrl) :
                new ObjectParameter("p_CategoryUrl", typeof(string));
    
            var p_ParentCategoryIdParameter = p_ParentCategoryId.HasValue ?
                new ObjectParameter("p_ParentCategoryId", p_ParentCategoryId) :
                new ObjectParameter("p_ParentCategoryId", typeof(int));
    
            var p_PageHeadingParameter = p_PageHeading != null ?
                new ObjectParameter("p_PageHeading", p_PageHeading) :
                new ObjectParameter("p_PageHeading", typeof(string));
    
            var p_TitleParameter = p_Title != null ?
                new ObjectParameter("p_Title", p_Title) :
                new ObjectParameter("p_Title", typeof(string));
    
            var p_TopDescriptionParameter = p_TopDescription != null ?
                new ObjectParameter("p_TopDescription", p_TopDescription) :
                new ObjectParameter("p_TopDescription", typeof(string));
    
            var p_MainPageImageParameter = p_MainPageImage != null ?
                new ObjectParameter("p_MainPageImage", p_MainPageImage) :
                new ObjectParameter("p_MainPageImage", typeof(string));
    
            var p_MainPageImageAltAttrParameter = p_MainPageImageAltAttr != null ?
                new ObjectParameter("p_MainPageImageAltAttr", p_MainPageImageAltAttr) :
                new ObjectParameter("p_MainPageImageAltAttr", typeof(string));
    
            var p_HomePageDescParameter = p_HomePageDesc != null ?
                new ObjectParameter("p_HomePageDesc", p_HomePageDesc) :
                new ObjectParameter("p_HomePageDesc", typeof(string));
    
            var p_HomePageImageParameter = p_HomePageImage != null ?
                new ObjectParameter("p_HomePageImage", p_HomePageImage) :
                new ObjectParameter("p_HomePageImage", typeof(string));
    
            var p_HomePageAltAttrParameter = p_HomePageAltAttr != null ?
                new ObjectParameter("p_HomePageAltAttr", p_HomePageAltAttr) :
                new ObjectParameter("p_HomePageAltAttr", typeof(string));
    
            var p_KeywordParameter = p_Keyword != null ?
                new ObjectParameter("p_Keyword", p_Keyword) :
                new ObjectParameter("p_Keyword", typeof(string));
    
            var p_MetaDescriptionParameter = p_MetaDescription != null ?
                new ObjectParameter("p_MetaDescription", p_MetaDescription) :
                new ObjectParameter("p_MetaDescription", typeof(string));
    
            var p_AppendIdParameter = p_AppendId.HasValue ?
                new ObjectParameter("p_AppendId", p_AppendId) :
                new ObjectParameter("p_AppendId", typeof(sbyte));
    
            var p_UserIdParameter = p_UserId.HasValue ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_AddCategory", p_CategoryNameParameter, p_CategoryUrlParameter, p_ParentCategoryIdParameter, p_PageHeadingParameter, p_TitleParameter, p_TopDescriptionParameter, p_MainPageImageParameter, p_MainPageImageAltAttrParameter, p_HomePageDescParameter, p_HomePageImageParameter, p_HomePageAltAttrParameter, p_KeywordParameter, p_MetaDescriptionParameter, p_Message, p_AppendIdParameter, p_UserIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Zion_AddReportinformation(string p_ReportTitle, string p_TableofContents, string p_ListOfTable, string p_ListOfFigure, string p_MainPageDescription, string p_SearchPageDescription, Nullable<System.DateTime> p_PublishDate, Nullable<decimal> p_PriceSingleUser, Nullable<decimal> p_PriceEnterpriseLicense, Nullable<decimal> p_PriceCUL, Nullable<int> p_Location, Nullable<decimal> p_DiscountPercentage, Nullable<int> p_NumberOfPage, Nullable<int> p_CategoryId, string p_MetaTitle, string p_MetaKeywords, string p_MetaDescription, string p_ListOfCharts, string p_ReportUrl, Nullable<sbyte> p_IsActive, Nullable<sbyte> p_IsUpComing, Nullable<int> p_CreatedBy, string p_Methodology, string p_FreeAnalysis, string p_MainPageImagePath, string p_MainPageImageAltAttribute, string p_SearchPageImagePath, string p_SearchPageImageAltAttribute, string p_Tags, ObjectParameter p_NewReportId, ObjectParameter p_ReportCategoryName, ObjectParameter p_NewReportUrl, ObjectParameter p_NewReportTitle, Nullable<sbyte> p_AppendId, Nullable<int> p_DeliveryFormat, string p_SampleMetaTitle, string p_SampleMetaDescription, string p_SampleMetaKeywords, string p_TOCMetaTile, string p_TOCMetaDescription, string p_TOCMetaKeywords, string p_FreeAnalysisMetaTitle, string p_FreeAnalysisMetaDescription, string p_FreeAnalysisMetaKeyords, string p_InquiryMetaTitle, string p_InquiryMetaDescription, string p_InquiryMetaKeywords)
        {
            var p_ReportTitleParameter = p_ReportTitle != null ?
                new ObjectParameter("p_ReportTitle", p_ReportTitle) :
                new ObjectParameter("p_ReportTitle", typeof(string));
    
            var p_TableofContentsParameter = p_TableofContents != null ?
                new ObjectParameter("p_TableofContents", p_TableofContents) :
                new ObjectParameter("p_TableofContents", typeof(string));
    
            var p_ListOfTableParameter = p_ListOfTable != null ?
                new ObjectParameter("p_ListOfTable", p_ListOfTable) :
                new ObjectParameter("p_ListOfTable", typeof(string));
    
            var p_ListOfFigureParameter = p_ListOfFigure != null ?
                new ObjectParameter("p_ListOfFigure", p_ListOfFigure) :
                new ObjectParameter("p_ListOfFigure", typeof(string));
    
            var p_MainPageDescriptionParameter = p_MainPageDescription != null ?
                new ObjectParameter("p_MainPageDescription", p_MainPageDescription) :
                new ObjectParameter("p_MainPageDescription", typeof(string));
    
            var p_SearchPageDescriptionParameter = p_SearchPageDescription != null ?
                new ObjectParameter("p_SearchPageDescription", p_SearchPageDescription) :
                new ObjectParameter("p_SearchPageDescription", typeof(string));
    
            var p_PublishDateParameter = p_PublishDate.HasValue ?
                new ObjectParameter("p_PublishDate", p_PublishDate) :
                new ObjectParameter("p_PublishDate", typeof(System.DateTime));
    
            var p_PriceSingleUserParameter = p_PriceSingleUser.HasValue ?
                new ObjectParameter("p_PriceSingleUser", p_PriceSingleUser) :
                new ObjectParameter("p_PriceSingleUser", typeof(decimal));
    
            var p_PriceEnterpriseLicenseParameter = p_PriceEnterpriseLicense.HasValue ?
                new ObjectParameter("p_PriceEnterpriseLicense", p_PriceEnterpriseLicense) :
                new ObjectParameter("p_PriceEnterpriseLicense", typeof(decimal));
    
            var p_PriceCULParameter = p_PriceCUL.HasValue ?
                new ObjectParameter("p_PriceCUL", p_PriceCUL) :
                new ObjectParameter("p_PriceCUL", typeof(decimal));
    
            var p_LocationParameter = p_Location.HasValue ?
                new ObjectParameter("p_Location", p_Location) :
                new ObjectParameter("p_Location", typeof(int));
    
            var p_DiscountPercentageParameter = p_DiscountPercentage.HasValue ?
                new ObjectParameter("p_DiscountPercentage", p_DiscountPercentage) :
                new ObjectParameter("p_DiscountPercentage", typeof(decimal));
    
            var p_NumberOfPageParameter = p_NumberOfPage.HasValue ?
                new ObjectParameter("p_NumberOfPage", p_NumberOfPage) :
                new ObjectParameter("p_NumberOfPage", typeof(int));
    
            var p_CategoryIdParameter = p_CategoryId.HasValue ?
                new ObjectParameter("p_CategoryId", p_CategoryId) :
                new ObjectParameter("p_CategoryId", typeof(int));
    
            var p_MetaTitleParameter = p_MetaTitle != null ?
                new ObjectParameter("p_MetaTitle", p_MetaTitle) :
                new ObjectParameter("p_MetaTitle", typeof(string));
    
            var p_MetaKeywordsParameter = p_MetaKeywords != null ?
                new ObjectParameter("p_MetaKeywords", p_MetaKeywords) :
                new ObjectParameter("p_MetaKeywords", typeof(string));
    
            var p_MetaDescriptionParameter = p_MetaDescription != null ?
                new ObjectParameter("p_MetaDescription", p_MetaDescription) :
                new ObjectParameter("p_MetaDescription", typeof(string));
    
            var p_ListOfChartsParameter = p_ListOfCharts != null ?
                new ObjectParameter("p_ListOfCharts", p_ListOfCharts) :
                new ObjectParameter("p_ListOfCharts", typeof(string));
    
            var p_ReportUrlParameter = p_ReportUrl != null ?
                new ObjectParameter("p_ReportUrl", p_ReportUrl) :
                new ObjectParameter("p_ReportUrl", typeof(string));
    
            var p_IsActiveParameter = p_IsActive.HasValue ?
                new ObjectParameter("p_IsActive", p_IsActive) :
                new ObjectParameter("p_IsActive", typeof(sbyte));
    
            var p_IsUpComingParameter = p_IsUpComing.HasValue ?
                new ObjectParameter("p_IsUpComing", p_IsUpComing) :
                new ObjectParameter("p_IsUpComing", typeof(sbyte));
    
            var p_CreatedByParameter = p_CreatedBy.HasValue ?
                new ObjectParameter("p_CreatedBy", p_CreatedBy) :
                new ObjectParameter("p_CreatedBy", typeof(int));
    
            var p_MethodologyParameter = p_Methodology != null ?
                new ObjectParameter("p_Methodology", p_Methodology) :
                new ObjectParameter("p_Methodology", typeof(string));
    
            var p_FreeAnalysisParameter = p_FreeAnalysis != null ?
                new ObjectParameter("p_FreeAnalysis", p_FreeAnalysis) :
                new ObjectParameter("p_FreeAnalysis", typeof(string));
    
            var p_MainPageImagePathParameter = p_MainPageImagePath != null ?
                new ObjectParameter("p_MainPageImagePath", p_MainPageImagePath) :
                new ObjectParameter("p_MainPageImagePath", typeof(string));
    
            var p_MainPageImageAltAttributeParameter = p_MainPageImageAltAttribute != null ?
                new ObjectParameter("p_MainPageImageAltAttribute", p_MainPageImageAltAttribute) :
                new ObjectParameter("p_MainPageImageAltAttribute", typeof(string));
    
            var p_SearchPageImagePathParameter = p_SearchPageImagePath != null ?
                new ObjectParameter("p_SearchPageImagePath", p_SearchPageImagePath) :
                new ObjectParameter("p_SearchPageImagePath", typeof(string));
    
            var p_SearchPageImageAltAttributeParameter = p_SearchPageImageAltAttribute != null ?
                new ObjectParameter("p_SearchPageImageAltAttribute", p_SearchPageImageAltAttribute) :
                new ObjectParameter("p_SearchPageImageAltAttribute", typeof(string));
    
            var p_TagsParameter = p_Tags != null ?
                new ObjectParameter("p_Tags", p_Tags) :
                new ObjectParameter("p_Tags", typeof(string));
    
            var p_AppendIdParameter = p_AppendId.HasValue ?
                new ObjectParameter("p_AppendId", p_AppendId) :
                new ObjectParameter("p_AppendId", typeof(sbyte));
    
            var p_DeliveryFormatParameter = p_DeliveryFormat.HasValue ?
                new ObjectParameter("p_DeliveryFormat", p_DeliveryFormat) :
                new ObjectParameter("p_DeliveryFormat", typeof(int));
    
            var p_SampleMetaTitleParameter = p_SampleMetaTitle != null ?
                new ObjectParameter("p_SampleMetaTitle", p_SampleMetaTitle) :
                new ObjectParameter("p_SampleMetaTitle", typeof(string));
    
            var p_SampleMetaDescriptionParameter = p_SampleMetaDescription != null ?
                new ObjectParameter("p_SampleMetaDescription", p_SampleMetaDescription) :
                new ObjectParameter("p_SampleMetaDescription", typeof(string));
    
            var p_SampleMetaKeywordsParameter = p_SampleMetaKeywords != null ?
                new ObjectParameter("p_SampleMetaKeywords", p_SampleMetaKeywords) :
                new ObjectParameter("p_SampleMetaKeywords", typeof(string));
    
            var p_TOCMetaTileParameter = p_TOCMetaTile != null ?
                new ObjectParameter("p_TOCMetaTile", p_TOCMetaTile) :
                new ObjectParameter("p_TOCMetaTile", typeof(string));
    
            var p_TOCMetaDescriptionParameter = p_TOCMetaDescription != null ?
                new ObjectParameter("p_TOCMetaDescription", p_TOCMetaDescription) :
                new ObjectParameter("p_TOCMetaDescription", typeof(string));
    
            var p_TOCMetaKeywordsParameter = p_TOCMetaKeywords != null ?
                new ObjectParameter("p_TOCMetaKeywords", p_TOCMetaKeywords) :
                new ObjectParameter("p_TOCMetaKeywords", typeof(string));
    
            var p_FreeAnalysisMetaTitleParameter = p_FreeAnalysisMetaTitle != null ?
                new ObjectParameter("p_FreeAnalysisMetaTitle", p_FreeAnalysisMetaTitle) :
                new ObjectParameter("p_FreeAnalysisMetaTitle", typeof(string));
    
            var p_FreeAnalysisMetaDescriptionParameter = p_FreeAnalysisMetaDescription != null ?
                new ObjectParameter("p_FreeAnalysisMetaDescription", p_FreeAnalysisMetaDescription) :
                new ObjectParameter("p_FreeAnalysisMetaDescription", typeof(string));
    
            var p_FreeAnalysisMetaKeyordsParameter = p_FreeAnalysisMetaKeyords != null ?
                new ObjectParameter("p_FreeAnalysisMetaKeyords", p_FreeAnalysisMetaKeyords) :
                new ObjectParameter("p_FreeAnalysisMetaKeyords", typeof(string));
    
            var p_InquiryMetaTitleParameter = p_InquiryMetaTitle != null ?
                new ObjectParameter("p_InquiryMetaTitle", p_InquiryMetaTitle) :
                new ObjectParameter("p_InquiryMetaTitle", typeof(string));
    
            var p_InquiryMetaDescriptionParameter = p_InquiryMetaDescription != null ?
                new ObjectParameter("p_InquiryMetaDescription", p_InquiryMetaDescription) :
                new ObjectParameter("p_InquiryMetaDescription", typeof(string));
    
            var p_InquiryMetaKeywordsParameter = p_InquiryMetaKeywords != null ?
                new ObjectParameter("p_InquiryMetaKeywords", p_InquiryMetaKeywords) :
                new ObjectParameter("p_InquiryMetaKeywords", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Zion_AddReportinformation", p_ReportTitleParameter, p_TableofContentsParameter, p_ListOfTableParameter, p_ListOfFigureParameter, p_MainPageDescriptionParameter, p_SearchPageDescriptionParameter, p_PublishDateParameter, p_PriceSingleUserParameter, p_PriceEnterpriseLicenseParameter, p_PriceCULParameter, p_LocationParameter, p_DiscountPercentageParameter, p_NumberOfPageParameter, p_CategoryIdParameter, p_MetaTitleParameter, p_MetaKeywordsParameter, p_MetaDescriptionParameter, p_ListOfChartsParameter, p_ReportUrlParameter, p_IsActiveParameter, p_IsUpComingParameter, p_CreatedByParameter, p_MethodologyParameter, p_FreeAnalysisParameter, p_MainPageImagePathParameter, p_MainPageImageAltAttributeParameter, p_SearchPageImagePathParameter, p_SearchPageImageAltAttributeParameter, p_TagsParameter, p_NewReportId, p_ReportCategoryName, p_NewReportUrl, p_NewReportTitle, p_AppendIdParameter, p_DeliveryFormatParameter, p_SampleMetaTitleParameter, p_SampleMetaDescriptionParameter, p_SampleMetaKeywordsParameter, p_TOCMetaTileParameter, p_TOCMetaDescriptionParameter, p_TOCMetaKeywordsParameter, p_FreeAnalysisMetaTitleParameter, p_FreeAnalysisMetaDescriptionParameter, p_FreeAnalysisMetaKeyordsParameter, p_InquiryMetaTitleParameter, p_InquiryMetaDescriptionParameter, p_InquiryMetaKeywordsParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Zion_AddUser(string p_UserName, string p_FirstName, string p_LastName, string p_Password, string p_EmailId, string p_UserRoles, ObjectParameter p_RowCount, Nullable<int> p_CreatedBy, string p_RegisteredIp, Nullable<sbyte> p_IsRemote)
        {
            var p_UserNameParameter = p_UserName != null ?
                new ObjectParameter("p_UserName", p_UserName) :
                new ObjectParameter("p_UserName", typeof(string));
    
            var p_FirstNameParameter = p_FirstName != null ?
                new ObjectParameter("p_FirstName", p_FirstName) :
                new ObjectParameter("p_FirstName", typeof(string));
    
            var p_LastNameParameter = p_LastName != null ?
                new ObjectParameter("p_LastName", p_LastName) :
                new ObjectParameter("p_LastName", typeof(string));
    
            var p_PasswordParameter = p_Password != null ?
                new ObjectParameter("p_Password", p_Password) :
                new ObjectParameter("p_Password", typeof(string));
    
            var p_EmailIdParameter = p_EmailId != null ?
                new ObjectParameter("p_EmailId", p_EmailId) :
                new ObjectParameter("p_EmailId", typeof(string));
    
            var p_UserRolesParameter = p_UserRoles != null ?
                new ObjectParameter("p_UserRoles", p_UserRoles) :
                new ObjectParameter("p_UserRoles", typeof(string));
    
            var p_CreatedByParameter = p_CreatedBy.HasValue ?
                new ObjectParameter("p_CreatedBy", p_CreatedBy) :
                new ObjectParameter("p_CreatedBy", typeof(int));
    
            var p_RegisteredIpParameter = p_RegisteredIp != null ?
                new ObjectParameter("p_RegisteredIp", p_RegisteredIp) :
                new ObjectParameter("p_RegisteredIp", typeof(string));
    
            var p_IsRemoteParameter = p_IsRemote.HasValue ?
                new ObjectParameter("p_IsRemote", p_IsRemote) :
                new ObjectParameter("p_IsRemote", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Zion_AddUser", p_UserNameParameter, p_FirstNameParameter, p_LastNameParameter, p_PasswordParameter, p_EmailIdParameter, p_UserRolesParameter, p_RowCount, p_CreatedByParameter, p_RegisteredIpParameter, p_IsRemoteParameter);
        }
    
        public virtual int Zion_UpdateRole(Nullable<int> p_RoleId, string p_RoleName, string p_Actions, ObjectParameter p_RowCount, Nullable<int> p_UpdatedBy)
        {
            var p_RoleIdParameter = p_RoleId.HasValue ?
                new ObjectParameter("p_RoleId", p_RoleId) :
                new ObjectParameter("p_RoleId", typeof(int));
    
            var p_RoleNameParameter = p_RoleName != null ?
                new ObjectParameter("p_RoleName", p_RoleName) :
                new ObjectParameter("p_RoleName", typeof(string));
    
            var p_ActionsParameter = p_Actions != null ?
                new ObjectParameter("p_Actions", p_Actions) :
                new ObjectParameter("p_Actions", typeof(string));
    
            var p_UpdatedByParameter = p_UpdatedBy.HasValue ?
                new ObjectParameter("p_UpdatedBy", p_UpdatedBy) :
                new ObjectParameter("p_UpdatedBy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_UpdateRole", p_RoleIdParameter, p_RoleNameParameter, p_ActionsParameter, p_RowCount, p_UpdatedByParameter);
        }
    
        public virtual int Zion_UpdateUser(Nullable<int> p_UserId, string p_UserName, string p_UserRoles, ObjectParameter p_RowCount, Nullable<int> p_UpdatedBy, string p_RoleIdList, string p_RegisteredIP, Nullable<sbyte> p_IsRemote)
        {
            var p_UserIdParameter = p_UserId.HasValue ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(int));
    
            var p_UserNameParameter = p_UserName != null ?
                new ObjectParameter("p_UserName", p_UserName) :
                new ObjectParameter("p_UserName", typeof(string));
    
            var p_UserRolesParameter = p_UserRoles != null ?
                new ObjectParameter("p_UserRoles", p_UserRoles) :
                new ObjectParameter("p_UserRoles", typeof(string));
    
            var p_UpdatedByParameter = p_UpdatedBy.HasValue ?
                new ObjectParameter("p_UpdatedBy", p_UpdatedBy) :
                new ObjectParameter("p_UpdatedBy", typeof(int));
    
            var p_RoleIdListParameter = p_RoleIdList != null ?
                new ObjectParameter("p_RoleIdList", p_RoleIdList) :
                new ObjectParameter("p_RoleIdList", typeof(string));
    
            var p_RegisteredIPParameter = p_RegisteredIP != null ?
                new ObjectParameter("p_RegisteredIP", p_RegisteredIP) :
                new ObjectParameter("p_RegisteredIP", typeof(string));
    
            var p_IsRemoteParameter = p_IsRemote.HasValue ?
                new ObjectParameter("p_IsRemote", p_IsRemote) :
                new ObjectParameter("p_IsRemote", typeof(sbyte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Zion_UpdateUser", p_UserIdParameter, p_UserNameParameter, p_UserRolesParameter, p_RowCount, p_UpdatedByParameter, p_RoleIdListParameter, p_RegisteredIPParameter, p_IsRemoteParameter);
        }
    
        public virtual ObjectResult<Zion_GetReportById_Result> Zion_GetReportById(Nullable<int> p_ReportId)
        {
            var p_ReportIdParameter = p_ReportId.HasValue ?
                new ObjectParameter("p_ReportId", p_ReportId) :
                new ObjectParameter("p_ReportId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zion_GetReportById_Result>("Zion_GetReportById", p_ReportIdParameter);
        }
    
        public virtual ObjectResult<Zion_GetZionInNewsLinks_Result> Zion_GetZionInNewsLinks(Nullable<int> p_limit, Nullable<int> p_page, ObjectParameter p_totalRecord)
        {
            var p_limitParameter = p_limit.HasValue ?
                new ObjectParameter("p_limit", p_limit) :
                new ObjectParameter("p_limit", typeof(int));
    
            var p_pageParameter = p_page.HasValue ?
                new ObjectParameter("p_page", p_page) :
                new ObjectParameter("p_page", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zion_GetZionInNewsLinks_Result>("Zion_GetZionInNewsLinks", p_limitParameter, p_pageParameter, p_totalRecord);
        }
    
        public virtual ObjectResult<Zion_GetAllPublishedReports_Result> Zion_GetAllFeaturedReports(Nullable<int> p_Page, string p_AttributeName, ObjectParameter p_TotalRecords)
        {
            var p_PageParameter = p_Page.HasValue ?
                new ObjectParameter("p_Page", p_Page) :
                new ObjectParameter("p_Page", typeof(int));
    
            var p_AttributeNameParameter = p_AttributeName != null ?
                new ObjectParameter("p_AttributeName", p_AttributeName) :
                new ObjectParameter("p_AttributeName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Zion_GetAllPublishedReports_Result>("Zion_GetAllFeaturedReports", p_PageParameter, p_AttributeNameParameter, p_TotalRecords);
        }
    }
}
