//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZionMarketResearch.CRM {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRM.WebServiceSoap")]
    public interface WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateWithDomainName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertUpdateWithDomainName(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int _DomainID, 
                    string DomainName, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateWithDomainName", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertUpdateWithDomainNameAsync(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int _DomainID, 
                    string DomainName, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertUpdateKey(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName, 
                    int PublisherID, 
                    string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateKey", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertUpdateKeyAsync(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName, 
                    int PublisherID, 
                    string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateKey_CatName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertUpdateKey_CatName(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName, 
                    int PublisherID, 
                    string Key, 
                    string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateKey_CatName", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertUpdateKey_CatNameAsync(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName, 
                    int PublisherID, 
                    string Key, 
                    string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateKeyLostLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertUpdateKeyLostLeads(
                    int ID, 
                    int AgentID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string PublisherName, 
                    int PublisherID, 
                    int CreatedBy, 
                    System.DateTime CreatedDate, 
                    string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateKeyLostLeads", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertUpdateKeyLostLeadsAsync(
                    int ID, 
                    int AgentID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string PublisherName, 
                    int PublisherID, 
                    int CreatedBy, 
                    System.DateTime CreatedDate, 
                    string Key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get(int Mode, int ID, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAsync(int Mode, int ID, string GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeads", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLeads(int Mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLeads", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLeadsAsync(int Mode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateAgentMachineInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int InsertUpdateAgentMachineInfo(int ID, int AgentID, string MACID, string CPUInformation, string LoginUser, int UserID, int IsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUpdateAgentMachineInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> InsertUpdateAgentMachineInfoAsync(int ID, int AgentID, string MACID, string CPUInformation, string LoginUser, int UserID, int IsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAgentMachineInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAgentMachineInfo(int ID, int AgentID, string MACID, string CPUInformation, string LoginUser, int UserID, int IsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAgentMachineInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAgentMachineInfoAsync(int ID, int AgentID, string MACID, string CPUInformation, string LoginUser, int UserID, int IsActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAgent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAgent(int Mode, string LoginName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAgent", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAgentAsync(int Mode, string LoginName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Test", ReplyAction="*")]
        System.Threading.Tasks.Task TestAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : ZionMarketResearch.CRM.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<ZionMarketResearch.CRM.WebServiceSoap>, ZionMarketResearch.CRM.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public int InsertUpdateWithDomainName(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int _DomainID, 
                    string DomainName, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName) {
            return base.Channel.InsertUpdateWithDomainName(ID, ReportID, ReportTitle, InquiryTypeID, _DomainID, DomainName, LeadCategoryID, LeadSourceID, SourceURL, IPAddress, Name, EmailID, ContactNo, NameOfCompany, Designation, Address, State, CountryName, ZipCode, Comments, IsActive, GUID, TransactionID, Token, PublisherName);
        }
        
        public System.Threading.Tasks.Task<int> InsertUpdateWithDomainNameAsync(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int _DomainID, 
                    string DomainName, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName) {
            return base.Channel.InsertUpdateWithDomainNameAsync(ID, ReportID, ReportTitle, InquiryTypeID, _DomainID, DomainName, LeadCategoryID, LeadSourceID, SourceURL, IPAddress, Name, EmailID, ContactNo, NameOfCompany, Designation, Address, State, CountryName, ZipCode, Comments, IsActive, GUID, TransactionID, Token, PublisherName);
        }
        
        public int InsertUpdateKey(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName, 
                    int PublisherID, 
                    string Key) {
            return base.Channel.InsertUpdateKey(ID, ReportID, ReportTitle, InquiryTypeID, DomainID, LeadCategoryID, LeadSourceID, SourceURL, IPAddress, Name, EmailID, ContactNo, NameOfCompany, Designation, Address, State, CountryName, ZipCode, Comments, IsActive, GUID, TransactionID, Token, PublisherName, PublisherID, Key);
        }
        
        public System.Threading.Tasks.Task<int> InsertUpdateKeyAsync(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName, 
                    int PublisherID, 
                    string Key) {
            return base.Channel.InsertUpdateKeyAsync(ID, ReportID, ReportTitle, InquiryTypeID, DomainID, LeadCategoryID, LeadSourceID, SourceURL, IPAddress, Name, EmailID, ContactNo, NameOfCompany, Designation, Address, State, CountryName, ZipCode, Comments, IsActive, GUID, TransactionID, Token, PublisherName, PublisherID, Key);
        }
        
        public int InsertUpdateKey_CatName(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName, 
                    int PublisherID, 
                    string Key, 
                    string CategoryName) {
            return base.Channel.InsertUpdateKey_CatName(ID, ReportID, ReportTitle, InquiryTypeID, DomainID, LeadCategoryID, LeadSourceID, SourceURL, IPAddress, Name, EmailID, ContactNo, NameOfCompany, Designation, Address, State, CountryName, ZipCode, Comments, IsActive, GUID, TransactionID, Token, PublisherName, PublisherID, Key, CategoryName);
        }
        
        public System.Threading.Tasks.Task<int> InsertUpdateKey_CatNameAsync(
                    int ID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string GUID, 
                    string TransactionID, 
                    string Token, 
                    string PublisherName, 
                    int PublisherID, 
                    string Key, 
                    string CategoryName) {
            return base.Channel.InsertUpdateKey_CatNameAsync(ID, ReportID, ReportTitle, InquiryTypeID, DomainID, LeadCategoryID, LeadSourceID, SourceURL, IPAddress, Name, EmailID, ContactNo, NameOfCompany, Designation, Address, State, CountryName, ZipCode, Comments, IsActive, GUID, TransactionID, Token, PublisherName, PublisherID, Key, CategoryName);
        }
        
        public int InsertUpdateKeyLostLeads(
                    int ID, 
                    int AgentID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string PublisherName, 
                    int PublisherID, 
                    int CreatedBy, 
                    System.DateTime CreatedDate, 
                    string Key) {
            return base.Channel.InsertUpdateKeyLostLeads(ID, AgentID, ReportID, ReportTitle, InquiryTypeID, DomainID, LeadCategoryID, LeadSourceID, SourceURL, IPAddress, Name, EmailID, ContactNo, NameOfCompany, Designation, Address, State, CountryName, ZipCode, Comments, IsActive, PublisherName, PublisherID, CreatedBy, CreatedDate, Key);
        }
        
        public System.Threading.Tasks.Task<int> InsertUpdateKeyLostLeadsAsync(
                    int ID, 
                    int AgentID, 
                    int ReportID, 
                    string ReportTitle, 
                    int InquiryTypeID, 
                    int DomainID, 
                    int LeadCategoryID, 
                    int LeadSourceID, 
                    string SourceURL, 
                    string IPAddress, 
                    string Name, 
                    string EmailID, 
                    string ContactNo, 
                    string NameOfCompany, 
                    string Designation, 
                    string Address, 
                    string State, 
                    string CountryName, 
                    string ZipCode, 
                    string Comments, 
                    int IsActive, 
                    string PublisherName, 
                    int PublisherID, 
                    int CreatedBy, 
                    System.DateTime CreatedDate, 
                    string Key) {
            return base.Channel.InsertUpdateKeyLostLeadsAsync(ID, AgentID, ReportID, ReportTitle, InquiryTypeID, DomainID, LeadCategoryID, LeadSourceID, SourceURL, IPAddress, Name, EmailID, ContactNo, NameOfCompany, Designation, Address, State, CountryName, ZipCode, Comments, IsActive, PublisherName, PublisherID, CreatedBy, CreatedDate, Key);
        }
        
        public System.Data.DataSet Get(int Mode, int ID, string GUID) {
            return base.Channel.Get(Mode, ID, GUID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAsync(int Mode, int ID, string GUID) {
            return base.Channel.GetAsync(Mode, ID, GUID);
        }
        
        public System.Data.DataSet GetLeads(int Mode) {
            return base.Channel.GetLeads(Mode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLeadsAsync(int Mode) {
            return base.Channel.GetLeadsAsync(Mode);
        }
        
        public int InsertUpdateAgentMachineInfo(int ID, int AgentID, string MACID, string CPUInformation, string LoginUser, int UserID, int IsActive) {
            return base.Channel.InsertUpdateAgentMachineInfo(ID, AgentID, MACID, CPUInformation, LoginUser, UserID, IsActive);
        }
        
        public System.Threading.Tasks.Task<int> InsertUpdateAgentMachineInfoAsync(int ID, int AgentID, string MACID, string CPUInformation, string LoginUser, int UserID, int IsActive) {
            return base.Channel.InsertUpdateAgentMachineInfoAsync(ID, AgentID, MACID, CPUInformation, LoginUser, UserID, IsActive);
        }
        
        public System.Data.DataSet GetAgentMachineInfo(int ID, int AgentID, string MACID, string CPUInformation, string LoginUser, int UserID, int IsActive) {
            return base.Channel.GetAgentMachineInfo(ID, AgentID, MACID, CPUInformation, LoginUser, UserID, IsActive);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAgentMachineInfoAsync(int ID, int AgentID, string MACID, string CPUInformation, string LoginUser, int UserID, int IsActive) {
            return base.Channel.GetAgentMachineInfoAsync(ID, AgentID, MACID, CPUInformation, LoginUser, UserID, IsActive);
        }
        
        public System.Data.DataSet GetAgent(int Mode, string LoginName, string Password) {
            return base.Channel.GetAgent(Mode, LoginName, Password);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAgentAsync(int Mode, string LoginName, string Password) {
            return base.Channel.GetAgentAsync(Mode, LoginName, Password);
        }
        
        public void Test() {
            base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task TestAsync() {
            return base.Channel.TestAsync();
        }
    }
}
